- name: variables from files
  hosts: local
  connection: local
  vars_files:    #keyword
  - course.yaml
  tasks:
  - name: print infor
    ansible.builtin.debug:
      msg: "Info : {{nme}}, {{designation}}"


  # Available to all tasks in that play