- name: Install pacakges
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "nginx", state: "absent"}
    - { name: "mysql", state: "absent"}
    - { name: "zip", state: "latest"}

#some i want to install and some uninstall

# - hosts: localhost
#   vars:
#     users:
#       - ram
#       - sam
#       - tom

#   tasks:
#     - name: Print users
#       debug:
#         msg: "{{ item }}"
#       loop: "{{ users }}"

# Loop in Ansible allows one task to run multiple times with different values.
# item is reserved