- name: create ec2 and r53 
  hosts: local
  connection: local
  vars:
   ami_id: ami-0220d79f3f480ecf5
   sg_id: sg-05070ca66b56218cd
   zone_id: Z026569833PO0BSJDM4X5
   domain_name: cloudskills.fun
   instances: 
   - mongodb
   tasks:
   - name: Creating ec2 instance
     amazon.aws.ec2_instance:
       name: "{{ item }}"
       instance_type: t2.micro
       security_group: "{{ sg_id }}"
       image_id: "{{ ami_id }}"
       tags:
         Name: "{{ item }}"
     loop: "{{ instances }}"
     register: ec2_output
    
   

  #  - name: printing the output
  #    ansible.builtin.debug:
  #       msg: "{{ ec2_output }}"

  #  - name: print public ipaddress
  #    ansible.builtin.debug:
  #       msg: "{{ item.instances[0].public_ip_address }}"
  #    loop: "{{ ec2_output.results }}"
    
  #  - name: print private ipaddress
  #    ansible.builtin.debug:
  #       msg: "{{ item.instances[0].private_ip_address }}"
  #    loop: "{{ ec2_output.results }}"
    
   - name: create route53 record 
     amazon.aws.route53: 
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{domain_name}}"    #mongodb.cloudskills.fun
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true 
     loop: "{{ ec2_output.results }}"
     