[mongodb]
mongodb.cloudskills.fun


[mysql]
mysql.cloudskills.fun


[redis]
redis.cloudskills.fun

[rabbitmq]
rabbitmq.cloudskills.fun

[catalogue]
catalogue.cloudskills.fun

[user]
user.cloudskills.fun

[cart]
cart.cloudskills.fun

[frontend]
172.31.31.10


[all:vars]
ansible_user=ec2-ansible_user
ansible_password=DevOps321

[local]
localhost

[local:vars]
nme=Vikas
designation=devops engineer